-- Paint+ By Jakejakey1208
-- Image!
 
term.setCursorPos(20,8)
write(' ')
term.setCursorPos(8,6)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(13,6)
write(' ')
term.setBackgroundColor(1)
term.setBackgroundColor(16)
term.setBackgroundColor(20736)
term.setCursorPos(4,5)
write(' ')
term.setCursorPos(15,7)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(16,8)
write(' ')
term.setBackgroundColor(20736)
term.setBackgroundColor(colors.black)
term.setCursorPos(15,7)
write(' ')
term.setBackgroundColor(20736)
term.setCursorPos(1,5)
write(' ')
term.setCursorPos(2,5)
write(' ')
term.setCursorPos(2,5)
write(' ')
term.setCursorPos(2,5)
write(' ')
term.setCursorPos(3,5)
write(' ')
term.setCursorPos(3,5)
write(' ')
term.setCursorPos(4,5)
write(' ')
term.setCursorPos(5,5)
write(' ')
term.setCursorPos(5,5)
write(' ')
term.setCursorPos(6,5)
write(' ')
term.setCursorPos(6,5)
write(' ')
term.setCursorPos(7,5)
write(' ')
term.setCursorPos(8,5)
write(' ')
term.setCursorPos(9,5)
write(' ')
term.setCursorPos(9,5)
write(' ')
term.setCursorPos(10,5)
write(' ')
term.setCursorPos(10,5)
write(' ')
term.setCursorPos(11,5)
write(' ')
term.setCursorPos(12,5)
write(' ')
term.setCursorPos(12,5)
write(' ')
term.setCursorPos(12,5)
write(' ')
term.setCursorPos(13,5)
write(' ')
term.setCursorPos(14,5)
write(' ')
term.setCursorPos(15,5)
write(' ')
term.setCursorPos(15,5)
write(' ')
term.setCursorPos(15,5)
write(' ')
term.setCursorPos(19,5)
write(' ')
term.setCursorPos(16,5)
write(' ')
term.setCursorPos(17,5)
write(' ')
term.setCursorPos(18,5)
write(' ')
term.setCursorPos(18,5)
write(' ')
term.setCursorPos(20,5)
write(' ')
term.setCursorPos(20,5)
write(' ')
term.setCursorPos(21,5)
write(' ')
term.setCursorPos(22,5)
write(' ')
term.setCursorPos(22,5)
write(' ')
term.setCursorPos(23,5)
write(' ')
term.setCursorPos(23,5)
write(' ')
term.setCursorPos(24,5)
write(' ')
term.setCursorPos(24,5)
write(' ')
term.setCursorPos(25,5)
write(' ')
term.setCursorPos(26,5)
write(' ')
term.setCursorPos(26,5)
write(' ')
term.setCursorPos(27,5)
write(' ')
term.setCursorPos(27,5)
write(' ')
term.setCursorPos(29,5)
write(' ')
term.setCursorPos(29,5)
write(' ')
term.setCursorPos(27,5)
write(' ')
term.setCursorPos(28,5)
write(' ')
term.setCursorPos(29,5)
write(' ')
term.setCursorPos(30,5)
write(' ')
term.setCursorPos(31,5)
write(' ')
term.setCursorPos(32,5)
write(' ')
term.setCursorPos(32,5)
write(' ')
term.setCursorPos(33,5)
write(' ')
term.setCursorPos(33,5)
write(' ')
term.setCursorPos(33,5)
write(' ')
term.setCursorPos(34,5)
write(' ')
term.setCursorPos(35,5)
write(' ')
term.setCursorPos(35,5)
write(' ')
term.setCursorPos(36,5)
write(' ')
term.setCursorPos(37,5)
write(' ')
term.setCursorPos(37,5)
write(' ')
term.setCursorPos(38,5)
write(' ')
term.setCursorPos(39,5)
write(' ')
term.setCursorPos(39,5)
write(' ')
term.setCursorPos(40,5)
write(' ')
term.setCursorPos(41,5)
write(' ')
term.setCursorPos(42,5)
write(' ')
term.setCursorPos(42,5)
write(' ')
term.setCursorPos(42,5)
write(' ')
term.setCursorPos(43,5)
write(' ')
term.setCursorPos(43,5)
write(' ')
term.setCursorPos(44,5)
write(' ')
term.setCursorPos(44,5)
write(' ')
term.setCursorPos(45,5)
write(' ')
term.setCursorPos(46,5)
write(' ')
term.setCursorPos(46,5)
write(' ')
term.setCursorPos(47,5)
write(' ')
term.setCursorPos(49,5)
write(' ')
term.setCursorPos(49,5)
write(' ')
term.setCursorPos(49,5)
write(' ')
term.setCursorPos(50,5)
write(' ')
term.setCursorPos(51,5)
write(' ')
term.setCursorPos(48,5)
write(' ')
term.setCursorPos(51,7)
write(' ')
term.setCursorPos(50,7)
write(' ')
term.setCursorPos(49,7)
write(' ')
term.setCursorPos(47,7)
write(' ')
term.setCursorPos(47,7)
write(' ')
term.setCursorPos(48,7)
write(' ')
term.setCursorPos(46,7)
write(' ')
term.setCursorPos(46,7)
write(' ')
term.setCursorPos(45,7)
write(' ')
term.setCursorPos(45,7)
write(' ')
term.setCursorPos(44,7)
write(' ')
term.setCursorPos(43,7)
write(' ')
term.setCursorPos(42,7)
write(' ')
term.setCursorPos(42,7)
write(' ')
term.setCursorPos(41,7)
write(' ')
term.setCursorPos(41,7)
write(' ')
term.setCursorPos(39,7)
write(' ')
term.setCursorPos(39,7)
write(' ')
term.setCursorPos(40,7)
write(' ')
term.setCursorPos(38,7)
write(' ')
term.setCursorPos(37,7)
write(' ')
term.setCursorPos(37,7)
write(' ')
term.setCursorPos(36,7)
write(' ')
term.setCursorPos(35,7)
write(' ')
term.setCursorPos(35,7)
write(' ')
term.setCursorPos(34,7)
write(' ')
term.setCursorPos(34,7)
write(' ')
term.setCursorPos(32,7)
write(' ')
term.setCursorPos(32,7)
write(' ')
term.setCursorPos(33,7)
write(' ')
term.setCursorPos(31,7)
write(' ')
term.setCursorPos(30,7)
write(' ')
term.setCursorPos(29,7)
write(' ')
term.setCursorPos(29,7)
write(' ')
term.setCursorPos(27,7)
write(' ')
term.setCursorPos(28,7)
write(' ')
term.setCursorPos(26,7)
write(' ')
term.setCursorPos(25,7)
write(' ')
term.setCursorPos(25,7)
write(' ')
term.setCursorPos(24,7)
write(' ')
term.setCursorPos(24,7)
write(' ')
term.setCursorPos(23,7)
write(' ')
term.setCursorPos(23,7)
write(' ')
term.setCursorPos(23,7)
write(' ')
term.setCursorPos(22,7)
write(' ')
term.setCursorPos(22,7)
write(' ')
term.setCursorPos(22,7)
write(' ')
term.setCursorPos(20,7)
write(' ')
term.setCursorPos(21,7)
write(' ')
term.setCursorPos(19,7)
write(' ')
term.setCursorPos(18,7)
write(' ')
term.setCursorPos(17,7)
write(' ')
term.setCursorPos(17,7)
write(' ')
term.setCursorPos(16,7)
write(' ')
term.setCursorPos(16,7)
write(' ')
term.setCursorPos(15,7)
write(' ')
term.setCursorPos(15,7)
write(' ')
term.setCursorPos(14,7)
write(' ')
term.setCursorPos(14,7)
write(' ')
term.setCursorPos(13,7)
write(' ')
term.setCursorPos(12,7)
write(' ')
term.setCursorPos(12,7)
write(' ')
term.setCursorPos(11,7)
write(' ')
term.setCursorPos(11,7)
write(' ')
term.setCursorPos(8,8)
write(' ')
term.setCursorPos(10,7)
write(' ')
term.setCursorPos(10,7)
write(' ')
term.setCursorPos(9,7)
write(' ')
term.setCursorPos(9,7)
write(' ')
term.setCursorPos(8,7)
write(' ')
term.setCursorPos(8,7)
write(' ')
term.setCursorPos(7,7)
write(' ')
term.setCursorPos(7,7)
write(' ')
term.setCursorPos(6,7)
write(' ')
term.setCursorPos(5,7)
write(' ')
term.setCursorPos(4,7)
write(' ')
term.setCursorPos(2,7)
write(' ')
term.setCursorPos(2,7)
write(' ')
term.setCursorPos(1,7)
write(' ')
term.setCursorPos(3,7)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(8,8)
write(' ')
term.setBackgroundColor(20736)
sleep(0.5)
term.setBackgroundColor(38416)
term.setBackgroundColor(16)
term.setBackgroundColor(20736)
term.setBackgroundColor(14641)
term.setBackgroundColor(625)
term.setBackgroundColor(2401)
term.setBackgroundColor(28561)
term.setBackgroundColor(256)
term.setBackgroundColor(10000)
term.setCursorPos(6,13)
write(' ')
term.setCursorPos(7,12)
write(' ')
term.setCursorPos(8,11)
write(' ')
term.setCursorPos(9,10)
write(' ')
term.setCursorPos(10,11)
write(' ')
term.setCursorPos(11,13)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(10,13)
write(' ')
term.setBackgroundColor(10000)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,13)
write(' ')
term.setBackgroundColor(10000)
term.setCursorPos(11,12)
write(' ')
term.setBackgroundColor(colors.white)
term.setCursorPos(12,13)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(12,13)
write(' ')
term.setBackgroundColor(10000)
term.setCursorPos(12,13)
write(' ')
term.setCursorPos(11,13)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(12,13)
write(' ')
term.setBackgroundColor(10000)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,13)
write(' ')
term.setBackgroundColor(10000)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,12)
write(' ')
term.setBackgroundColor(10000)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,13)
write(' ')
term.setBackgroundColor(10000)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,12)
write(' ')
term.setBackgroundColor(10000)
term.setCursorPos(11,12)
write(' ')
term.setCursorPos(12,13)
write(' ')
term.setCursorPos(13,14)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(13,14)
write(' ')
term.setBackgroundColor(10000)
term.setCursorPos(11,15)
write(' ')
term.setCursorPos(11,14)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(11,15)
write(' ')
term.setBackgroundColor(10000)
term.setCursorPos(9,15)
write(' ')
term.setCursorPos(10,15)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(8,15)
write(' ')
term.setBackgroundColor(10000)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,15)
write(' ')
term.setBackgroundColor(10000)
term.setCursorPos(9,16)
write(' ')
term.setCursorPos(8,15)
write(' ')
term.setCursorPos(7,14)
write(' ')
term.setBackgroundColor(256)
term.setBackgroundColor(4096)
term.setCursorPos(6,14)
write(' ')
term.setCursorPos(6,15)
write(' ')
term.setCursorPos(6,16)
write(' ')
term.setCursorPos(6,16)
write(' ')
term.setCursorPos(6,17)
write(' ')
term.setCursorPos(7,15)
write(' ')
term.setCursorPos(7,16)
write(' ')
term.setCursorPos(7,17)
write(' ')
term.setCursorPos(7,17)
write(' ')
term.setCursorPos(7,18)
write(' ')
term.setCursorPos(8,16)
write(' ')
term.setCursorPos(8,17)
write(' ')
term.setCursorPos(9,18)
write(' ')
term.setCursorPos(8,18)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(9,18)
write(' ')
term.setBackgroundColor(4096)
term.setBackgroundColor(colors.black)
term.setCursorPos(7,18)
write(' ')
term.setBackgroundColor(4096)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,18)
write(' ')
term.setBackgroundColor(4096)
term.setBackgroundColor(colors.black)
term.setCursorPos(6,18)
write(' ')
term.setBackgroundColor(4096)
term.setBackgroundColor(colors.black)
term.setCursorPos(6,17)
write(' ')
term.setBackgroundColor(4096)
term.setCursorPos(8,18)
write(' ')
term.setCursorPos(9,17)
write(' ')
term.setCursorPos(9,18)
write(' ')
term.setCursorPos(10,18)
write(' ')
term.setCursorPos(10,17)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(10,18)
write(' ')
term.setBackgroundColor(4096)
term.setCursorPos(10,18)
write(' ')
term.setCursorPos(10,16)
write(' ')
term.setCursorPos(11,17)
write(' ')
term.setCursorPos(10,16)
write(' ')
term.setCursorPos(11,16)
write(' ')
term.setCursorPos(12,16)
write(' ')
term.setCursorPos(12,15)
write(' ')
term.setCursorPos(11,15)
write(' ')
term.setCursorPos(12,14)
write(' ')
term.setBackgroundColor(6561)
term.setBackgroundColor(625)
term.setBackgroundColor(28561)
term.setBackgroundColor(28561)
term.setBackgroundColor(4096)
term.setBackgroundColor(4096)
term.setBackgroundColor(2401)
term.setBackgroundColor(625)
term.setBackgroundColor(10000)
term.setBackgroundColor(1296)
term.setBackgroundColor(16)
term.setBackgroundColor(2401)
term.setBackgroundColor(16)
term.setBackgroundColor(28561)
term.setBackgroundColor(625)
term.setBackgroundColor(81)
term.setBackgroundColor(20736)
term.setBackgroundColor(81)
term.setBackgroundColor(256)
term.setBackgroundColor(4096)
term.setBackgroundColor(10000)
term.setBackgroundColor(10000)
term.setCursorPos(11,13)
write(' ')
term.setCursorPos(10,13)
write(' ')
term.setCursorPos(9,15)
write(' ')
term.setCursorPos(10,14)
write(' ')
term.setCursorPos(9,14)
write(' ')
term.setCursorPos(8,13)
write(' ')
term.setCursorPos(8,14)
write(' ')
term.setCursorPos(7,13)
write(' ')
term.setCursorPos(8,13)
write(' ')
term.setCursorPos(9,13)
write(' ')
term.setCursorPos(9,13)
write(' ')
term.setCursorPos(9,12)
write(' ')
term.setCursorPos(10,12)
write(' ')
term.setCursorPos(8,11)
write(' ')
term.setCursorPos(9,11)
write(' ')
term.setCursorPos(8,12)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(9,10)
write(' ')
term.setBackgroundColor(10000)
term.setBackgroundColor(81)
term.setBackgroundColor(10000)
term.setBackgroundColor(20736)
term.setBackgroundColor(2401)
sleep(0.5)
term.setCursorPos(1,6)
write(' ')
term.setCursorPos(2,6)
write(' ')
sleep(0.5)
term.setCursorPos(3,6)
write(' ')
term.setCursorPos(4,6)
write(' ')
sleep(0.5)
term.setCursorPos(6,6)
write(' ')
term.setCursorPos(5,6)
write(' ')
sleep(0.5)
term.setCursorPos(7,6)
write(' ')
term.setCursorPos(8,6)
write(' ')
term.setCursorPos(9,6)
write(' ')
sleep(0.5)
term.setCursorPos(10,6)
write(' ')
term.setCursorPos(11,6)
write(' ')
term.setCursorPos(12,6)
write(' ')
sleep(0.5)
term.setCursorPos(13,6)
write(' ')
term.setCursorPos(14,6)
write(' ')
term.setCursorPos(15,6)
write(' ')
sleep(0.5)
term.setCursorPos(16,6)
write(' ')
term.setCursorPos(17,6)
write(' ')
term.setCursorPos(18,6)
write(' ')
sleep(0.5)
term.setCursorPos(20,6)
write(' ')
term.setCursorPos(19,6)
write(' ')
sleep(0.5)
term.setCursorPos(21,6)
write(' ')
term.setCursorPos(23,6)
write(' ')
term.setCursorPos(23,6)
write(' ')
term.setCursorPos(22,6)
write(' ')
term.setCursorPos(24,6)
write(' ')
sleep(0.5)
term.setCursorPos(25,6)
write(' ')
term.setCursorPos(26,6)
write(' ')
term.setCursorPos(27,6)
write(' ')
sleep(0.5)
term.setCursorPos(28,6)
write(' ')
term.setCursorPos(29,6)
write(' ')
term.setCursorPos(30,6)
write(' ')
sleep(0.5)
term.setCursorPos(31,6)
write(' ')
term.setCursorPos(32,6)
write(' ')
term.setCursorPos(33,6)
write(' ')
term.setCursorPos(33,6)
write(' ')
term.setCursorPos(34,6)
write(' ')
sleep(0.5)
term.setCursorPos(35,6)
write(' ')
term.setCursorPos(36,6)
write(' ')
term.setCursorPos(37,6)
write(' ')
term.setCursorPos(38,6)
write(' ')
sleep(0.5)
term.setCursorPos(39,6)
write(' ')
term.setCursorPos(39,6)
write(' ')
term.setCursorPos(41,6)
write(' ')
term.setCursorPos(41,6)
write(' ')
term.setCursorPos(42,6)
write(' ')
term.setCursorPos(40,6)
write(' ')
sleep(0.5)
term.setCursorPos(43,6)
write(' ')
term.setCursorPos(44,6)
write(' ')
term.setCursorPos(45,6)
write(' ')
term.setCursorPos(45,6)
write(' ')
term.setCursorPos(46,6)
write(' ')
term.setCursorPos(47,6)
write(' ')
sleep(0.5)
term.setCursorPos(48,6)
write(' ')
term.setCursorPos(51,7)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(51,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(38416)
term.setBackgroundColor(14641)
term.setBackgroundColor(10000)
term.setBackgroundColor(38416)
term.setBackgroundColor(4096)
term.setBackgroundColor(50625)
term.setBackgroundColor(256)
term.setBackgroundColor(10000)
term.setBackgroundColor(2401)
term.setBackgroundColor(16)
term.setBackgroundColor(4096)
term.setBackgroundColor(1296)
term.setBackgroundColor(14641)
term.setBackgroundColor(16)
term.setBackgroundColor(4096)
term.setBackgroundColor(16)
term.setBackgroundColor(16)
term.setBackgroundColor(4096)
term.setBackgroundColor(2401)
term.setBackgroundColor(20736)
term.setCursorPos(51,7)
write(' ')
term.setBackgroundColor(6561)
term.setBackgroundColor(38416)
term.setBackgroundColor(2401)
term.setBackgroundColor(50625)
term.setBackgroundColor(6561)
term.setBackgroundColor(28561)
term.setBackgroundColor(256)
term.setBackgroundColor(14641)
term.setBackgroundColor(1)
term.setBackgroundColor(20736)
term.setBackgroundColor(14641)
term.setBackgroundColor(50625)
term.setBackgroundColor(38416)
term.setBackgroundColor(81)
term.setBackgroundColor(28561)
sleep(0.5)
term.setBackgroundColor(50625)
term.setBackgroundColor(14641)
term.setBackgroundColor(6561)
term.setBackgroundColor(625)
term.setCursorPos(49,6)
write(' ')
term.setBackgroundColor(colors.black)
term.setCursorPos(49,6)
write(' ')
term.setBackgroundColor(625)
term.setBackgroundColor(16)
term.setBackgroundColor(20736)
term.setBackgroundColor(81)
term.setBackgroundColor(625)
term.setBackgroundColor(14641)
term.setBackgroundColor(6561)
term.setBackgroundColor(1296)
term.setBackgroundColor(256)
term.setBackgroundColor(28561)
term.setBackgroundColor(16)
term.setBackgroundColor(10000)
term.setBackgroundColor(38416)
term.setBackgroundColor(2401)
term.setCursorPos(49,6)
write(' ')
term.setCursorPos(50,6)
write(' ')
term.setCursorPos(51,6)
write(' ')
sleep(0.5)
term.setBackgroundColor(colors.black)
term.setCursorPos(51,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(50,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(47,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(47,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(48,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(49,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(46,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(46,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(45,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(45,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(44,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(43,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(43,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(41,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(40,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(40,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(41,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(42,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(40,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(39,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(39,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(38,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(37,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(36,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(36,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(35,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(34,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(33,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(32,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(32,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(31,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(31,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(30,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(30,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(29,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(28,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(27,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(27,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(26,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(25,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(24,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(24,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(22,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(23,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(20,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(21,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(19,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(18,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(18,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(17,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(16,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(15,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(15,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(13,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(14,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(13,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(12,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(7,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(6,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(5,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(4,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(2,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(3,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(1,7)
write(' ')
term.setBackgroundColor(2401)
sleep(0.5)
term.setBackgroundColor(colors.black)
term.setCursorPos(1,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(2,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(3,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(3,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(4,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(5,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(5,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(6,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(6,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(7,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(12,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(12,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(13,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(14,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(14,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(15,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(15,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(16,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(16,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(17,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(19,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(19,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(18,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(19,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(20,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(20,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(21,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(22,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(22,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(22,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(23,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(23,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(24,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(26,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(25,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(28,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(27,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(27,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(28,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(29,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(29,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(29,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(32,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(30,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(31,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(31,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(31,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(32,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(34,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(34,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(34,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(33,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(35,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(36,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(36,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(36,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(37,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(37,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(38,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(39,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(39,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(40,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(41,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(42,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(42,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(42,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(43,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(44,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(44,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(44,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(46,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(47,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(48,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(48,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(49,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(51,7)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(51,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(50,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(44,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(45,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(51,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(51,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(50,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(49,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(49,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(48,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(48,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(47,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(47,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(45,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(45,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(46,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(44,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(43,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(42,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(42,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(41,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(40,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(40,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(39,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(38,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(37,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(37,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(36,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(36,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(35,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(34,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(33,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(32,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(31,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(31,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(30,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(29,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(28,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(27,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(27,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(26,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(25,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(25,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(23,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(24,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(22,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(21,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(20,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(19,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(18,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(17,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(16,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(15,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(14,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(13,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(12,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(7,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(4,6)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(5,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(6,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(4,4)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(4,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(2,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(2,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(3,5)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(1,5)
write(' ')
term.setBackgroundColor(2401)
sleep(0.5)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,11)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,11)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,11)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,11)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,12)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(12,13)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(7,12)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(6,13)
write(' ')
term.setBackgroundColor(2401)
sleep(0.5)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,12)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,12)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,12)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,12)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,12)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,13)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(12,14)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(7,13)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(6,14)
write(' ')
term.setBackgroundColor(2401)
sleep(0.5)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,13)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,13)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,13)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,13)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(7,14)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(6,15)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(12,15)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,14)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,14)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,13)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,14)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,14)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,14)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(7,15)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(6,16)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,15)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(12,16)
write(' ')
term.setBackgroundColor(2401)
sleep(0.5)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,16)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,15)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,15)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(7,16)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,15)
write(' ')
term.setBackgroundColor(2401)
sleep(0.5)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,16)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,16)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,16)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,16)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(11,17)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(7,17)
write(' ')
term.setBackgroundColor(2401)
sleep(0.5)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,17)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,17)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(8,18)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,18)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,17)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,17)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,17)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(10,17)
write(' ')
term.setBackgroundColor(2401)
term.setBackgroundColor(colors.black)
term.setCursorPos(9,18)
write(' ')
term.setBackgroundColor(2401)
sleep(0.5)
